apiVersion: helm.earnix.com/v1alpha1
kind: HelmEOLAlert
metadata:
  labels:
    app.kubernetes.io/name: eol-operator
    app.kubernetes.io/managed-by: kustomize
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  namespace: cert-manager
  chartName: cert-manager
  installedVersion: "1.11.0"
  latestVersion: "1.16.3"
  versionsBehind: 5
  severity: minor
