/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// HelmEOLAlertSpec describes WHAT the operator detected — it is the "source of truth"
// snapshot written at alert creation time and refreshed every 6h by reconcileNotified.
// Think of it as the "desired state" field: it says "this release SHOULD be upgraded".
type HelmEOLAlertSpec struct {
	// ReleaseName is the Helm release name, e.g. "cert-manager".
	// This is the name you gave when running `helm install <ReleaseName> ...`.
	ReleaseName string `json:"releaseName"`

	// Namespace is the Kubernetes namespace the Helm release lives in.
	Namespace string `json:"namespace"`

	// ChartName is the upstream chart identifier, e.g. "cert-manager".
	// A single ChartName can have multiple releases (e.g. dev, staging, prod).
	ChartName string `json:"chartName"`

	// InstalledVersion is the semver string that is currently running in the cluster,
	// e.g. "13.0.0". Captured once at alert creation.
	InstalledVersion string `json:"installedVersion"`

	// LatestVersion is the newest non-prerelease version found on ArtifactHub
	// at the time of the last check, e.g. "24.0.2".
	LatestVersion string `json:"latestVersion"`

	// VersionsBehind is how many minor or major increments separate InstalledVersion
	// from LatestVersion. Used to prioritise alerts: 11 versions behind is worse than 1.
	VersionsBehind int `json:"versionsBehind"`

	// Severity classifies how urgent the upgrade is:
	//   "minor" — same major version, patch/minor updates available
	//   "major" — one full major version behind (breaking changes likely)
	//   "eol"   — two or more major versions behind (consider this unsupported)
	Severity string `json:"severity"`
}

// HelmEOLAlertStatus is written by the operator as it processes the alert.
// It records what has been DONE (enrichment, notifications) not what needs to be done.
// kubebuilder separates spec (desired) from status (observed) — they are updated
// via different API calls to avoid conflicts.
type HelmEOLAlertStatus struct {
	// AIReportGenerated is true once the Claude API enrichment has completed
	// and UpgradePath + RiskScore have been populated.
	AIReportGenerated bool `json:"aiReportGenerated"`

	// NotificationsSent is the list of channels that have already received this alert,
	// e.g. ["teams", "pagerduty"]. Used to prevent duplicate notifications on requeue.
	// omitempty means a nil slice is omitted from the JSON, avoiding a CRD validation
	// error for "required value".
	NotificationsSent []string `json:"notificationsSent,omitempty"`

	// UpgradePath is the step-by-step upgrade route generated by the AI enricher,
	// e.g. "13.0.0 → 18.0.0 → 24.0.2 (skip 16.x, breaking CRD changes in 19.0)".
	// Empty until AIReportGenerated = true.
	UpgradePath string `json:"upgradePath,omitempty"`

	// RiskScore is a 1–10 integer produced by the AI enricher.
	// 1 = trivial patch, 10 = critical / active CVE, immediate action required.
	RiskScore int `json:"riskScore,omitempty"`

	// LastChecked is the timestamp of the most recent version check against ArtifactHub.
	// Pointer so it can be omitted (nil) before the first check completes.
	LastChecked *metav1.Time `json:"lastChecked,omitempty"`

	// Phase is the current lifecycle stage of this alert:
	//   ""            / "Pending"     — just created, not yet processed
	//   "Enriching"   — AI report is being generated
	//   "Notified"    — notifications sent, polling every 6h for upgrade
	//   "Acknowledged"— a human has acknowledged; operator will not re-notify
	Phase string `json:"phase"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
//
// The two markers above tell kubebuilder:
//   - object:root=true  → this type is a top-level CRD (not just a nested struct)
//   - subresource:status → the /status sub-resource is separate from the main object.
//     This means r.Update() changes spec, and r.Status().Update() changes status.
//     They use different API paths so they cannot overwrite each other accidentally.

// HelmEOLAlert is the Schema for the helmeolalerts API.
// One HelmEOLAlert is created per outdated Helm release, in the same namespace
// as the release itself. Its name equals the Helm release name.
type HelmEOLAlert struct {
	// TypeMeta holds the apiVersion and kind fields ("helm.earnix.com/v1alpha1" / "HelmEOLAlert").
	// ",inline" means these fields appear at the top level of the YAML, not nested.
	metav1.TypeMeta `json:",inline"`

	// ObjectMeta holds standard Kubernetes metadata: name, namespace, labels,
	// annotations, resourceVersion (used for optimistic concurrency), etc.
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty,omitzero"`

	// Spec is what the operator detected — written once at creation.
	// +required
	Spec HelmEOLAlertSpec `json:"spec"`

	// Status is the operator's running journal of what it has done with this alert.
	// +optional
	Status HelmEOLAlertStatus `json:"status,omitempty,omitzero"`
}

// +kubebuilder:object:root=true

// HelmEOLAlertList is required by the controller-runtime framework.
// Any CRD type needs a corresponding List type so the API server can return
// collections (e.g. kubectl get helmeolalerts -A).
type HelmEOLAlertList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []HelmEOLAlert `json:"items"`
}

// init() runs automatically when the package is loaded.
// SchemeBuilder.Register tells the controller-runtime scheme about our types so
// that it knows how to encode/decode HelmEOLAlert objects to/from JSON/YAML.
// Without this, r.Get() and r.Create() would not know what Go struct to use.
func init() {
	SchemeBuilder.Register(&HelmEOLAlert{}, &HelmEOLAlertList{})
}
