/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// main is the operator entry point. It:
//  1. Parses CLI flags (metrics address, TLS config, leader election, etc.)
//  2. Creates the controller-runtime Manager — the central object that owns the
//     k8s client, scheme, leader election, health probes, and all controllers.
//  3. Wires up optional dependencies (AI enricher, notifiers) from env vars.
//  4. Registers the HelmEOLAlert reconciler with the Manager.
//  5. Starts the Manager's blocking run loop.
package main

import (
	"crypto/tls"
	"flag"
	"os"
	"path/filepath"

	"github.com/asafd/eol-operator/internal/agent"
	"github.com/asafd/eol-operator/internal/notifier"

	// Registers cloud-provider auth plugins (Azure, GCP, OIDC, etc.) so that
	// the in-cluster client can authenticate against managed k8s offerings.
	// Blank import — side-effect only (init() registers the plugins).
	_ "k8s.io/client-go/plugin/pkg/client/auth"

	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/certwatcher"
	"sigs.k8s.io/controller-runtime/pkg/healthz"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
	"sigs.k8s.io/controller-runtime/pkg/metrics/filters"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
	"sigs.k8s.io/controller-runtime/pkg/webhook"

	helmv1alpha1 "github.com/asafd/eol-operator/api/v1alpha1"
	"github.com/asafd/eol-operator/internal/controller"
	"github.com/asafd/eol-operator/internal/helm"
	// +kubebuilder:scaffold:imports
)

var (
	// scheme is the runtime.Scheme — a registry that maps Go types to Kubernetes
	// GroupVersionKinds (e.g. HelmEOLAlert → helmv1alpha1/HelmEOLAlert).
	// The Manager uses it to encode/decode objects from the API server.
	scheme = runtime.NewScheme()

	// setupLog is a structured logger scoped to the "setup" phase (before the
	// Manager starts). After start-up, controllers use log.FromContext(ctx) instead.
	setupLog = ctrl.Log.WithName("setup")
)

func init() {
	// Register the standard Kubernetes types (Pod, Secret, Deployment, etc.)
	// so the controller-runtime client can work with them.
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))

	// Register our custom CRD type (HelmEOLAlert) so the client can read/write it.
	// Generated by `make manifests` from the +kubebuilder markers in api/v1alpha1/.
	utilruntime.Must(helmv1alpha1.AddToScheme(scheme))
	// +kubebuilder:scaffold:scheme
}

// nolint:gocyclo
func main() {
	// -------------------------------------------------------------------------
	// 1. CLI flags
	// These are passed when the operator pod starts, e.g.:
	//   args: ["--leader-elect", "--metrics-bind-address=:8443"]
	// In development, you can pass them directly: `go run ./cmd/main.go --leader-elect=false`
	// -------------------------------------------------------------------------
	var metricsAddr string
	var metricsCertPath, metricsCertName, metricsCertKey string
	var webhookCertPath, webhookCertName, webhookCertKey string
	var enableLeaderElection bool
	var probeAddr string
	var secureMetrics bool
	var enableHTTP2 bool
	var tlsOpts []func(*tls.Config)
	flag.StringVar(&metricsAddr, "metrics-bind-address", "0", "The address the metrics endpoint binds to. "+
		"Use :8443 for HTTPS or :8080 for HTTP, or leave as 0 to disable the metrics service.")
	flag.StringVar(&probeAddr, "health-probe-bind-address", ":8081", "The address the probe endpoint binds to.")
	flag.BoolVar(&enableLeaderElection, "leader-elect", false,
		"Enable leader election for controller manager. "+
			"Enabling this will ensure there is only one active controller manager.")
	flag.BoolVar(&secureMetrics, "metrics-secure", true,
		"If set, the metrics endpoint is served securely via HTTPS. Use --metrics-secure=false to use HTTP instead.")
	flag.StringVar(&webhookCertPath, "webhook-cert-path", "", "The directory that contains the webhook certificate.")
	flag.StringVar(&webhookCertName, "webhook-cert-name", "tls.crt", "The name of the webhook certificate file.")
	flag.StringVar(&webhookCertKey, "webhook-cert-key", "tls.key", "The name of the webhook key file.")
	flag.StringVar(&metricsCertPath, "metrics-cert-path", "",
		"The directory that contains the metrics server certificate.")
	flag.StringVar(&metricsCertName, "metrics-cert-name", "tls.crt", "The name of the metrics server certificate file.")
	flag.StringVar(&metricsCertKey, "metrics-cert-key", "tls.key", "The name of the metrics server key file.")
	flag.BoolVar(&enableHTTP2, "enable-http2", false,
		"If set, HTTP/2 will be enabled for the metrics and webhook servers")
	// zap flags add --zap-log-level, --zap-encoder, --zap-stacktrace-level, etc.
	opts := zap.Options{
		Development: true, // human-readable log format; switch to false for JSON in production
	}
	opts.BindFlags(flag.CommandLine)
	flag.Parse()

	// Install the zap logger as the global logger used by controller-runtime.
	// After this point, every log.FromContext(ctx) call in the controllers
	// returns a logger backed by zap.
	ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))

	// -------------------------------------------------------------------------
	// 2. TLS hardening
	// HTTP/2 is disabled by default to avoid the Stream Cancellation (CVE-2023-44487)
	// and Rapid Reset (CVE-2023-39325) vulnerabilities. Enable only if you have
	// a specific need and have patched the underlying Go net/http library.
	// -------------------------------------------------------------------------
	disableHTTP2 := func(c *tls.Config) {
		setupLog.Info("disabling http/2")
		c.NextProtos = []string{"http/1.1"}
	}

	if !enableHTTP2 {
		tlsOpts = append(tlsOpts, disableHTTP2)
	}

	// -------------------------------------------------------------------------
	// 3. Certificate watchers (optional)
	// certwatcher hot-reloads TLS certificates from disk without restarting the
	// pod. This is used when cert-manager (or another PKI tool) rotates certs.
	// If no cert path is given, controller-runtime auto-generates a self-signed
	// cert — fine for development, not for production.
	// -------------------------------------------------------------------------
	var metricsCertWatcher, webhookCertWatcher *certwatcher.CertWatcher

	// webhookTLSOpts starts as a copy of the base tlsOpts so that the webhook
	// server and metrics server can have independent TLS configurations.
	webhookTLSOpts := tlsOpts

	if len(webhookCertPath) > 0 {
		setupLog.Info("Initializing webhook certificate watcher using provided certificates",
			"webhook-cert-path", webhookCertPath, "webhook-cert-name", webhookCertName, "webhook-cert-key", webhookCertKey)

		var err error
		// certwatcher.New reads the cert/key from disk and starts an inotify watcher.
		// When the files change (cert rotation), it reloads them in-memory.
		webhookCertWatcher, err = certwatcher.New(
			filepath.Join(webhookCertPath, webhookCertName),
			filepath.Join(webhookCertPath, webhookCertKey),
		)
		if err != nil {
			setupLog.Error(err, "Failed to initialize webhook certificate watcher")
			os.Exit(1)
		}

		// GetCertificate is called on every new TLS handshake — it always returns
		// the latest cert that certwatcher has loaded, so rotations take effect
		// without downtime.
		webhookTLSOpts = append(webhookTLSOpts, func(config *tls.Config) {
			config.GetCertificate = webhookCertWatcher.GetCertificate
		})
	}

	// webhookServer handles admission webhooks (ValidatingWebhookConfiguration,
	// MutatingWebhookConfiguration). We don't define any webhooks in this operator,
	// but the Manager scaffold requires a webhook server to be registered.
	webhookServer := webhook.NewServer(webhook.Options{
		TLSOpts: webhookTLSOpts,
	})

	// -------------------------------------------------------------------------
	// 4. Metrics server
	// The metrics endpoint exposes Prometheus-compatible metrics about the
	// controller (reconcile count, error rate, queue depth, etc.).
	// Enabled via config/default/kustomization.yaml; scrape with Prometheus.
	// -------------------------------------------------------------------------
	metricsServerOptions := metricsserver.Options{
		BindAddress:   metricsAddr,
		SecureServing: secureMetrics,
		TLSOpts:       tlsOpts,
	}

	if secureMetrics {
		// WithAuthenticationAndAuthorization gates the /metrics endpoint using the
		// cluster's TokenReview and SubjectAccessReview APIs — only subjects with
		// the "get" verb on the metrics resource can scrape it.
		// RBAC for this is in config/rbac/kustomization.yaml.
		metricsServerOptions.FilterProvider = filters.WithAuthenticationAndAuthorization
	}

	// Same hot-reload pattern as the webhook cert watcher above.
	// If no cert is provided, a self-signed cert is generated automatically
	// (fine for dev/test; in production, supply one via cert-manager).
	if len(metricsCertPath) > 0 {
		setupLog.Info("Initializing metrics certificate watcher using provided certificates",
			"metrics-cert-path", metricsCertPath, "metrics-cert-name", metricsCertName, "metrics-cert-key", metricsCertKey)

		var err error
		metricsCertWatcher, err = certwatcher.New(
			filepath.Join(metricsCertPath, metricsCertName),
			filepath.Join(metricsCertPath, metricsCertKey),
		)
		if err != nil {
			setupLog.Error(err, "to initialize metrics certificate watcher", "error", err)
			os.Exit(1)
		}

		metricsServerOptions.TLSOpts = append(metricsServerOptions.TLSOpts, func(config *tls.Config) {
			config.GetCertificate = metricsCertWatcher.GetCertificate
		})
	}

	// -------------------------------------------------------------------------
	// 5. Manager
	// The Manager is the heart of a controller-runtime operator. It owns:
	//   - A shared k8s client (caching, watches) for all controllers
	//   - Leader election (only one replica is active at a time)
	//   - Health/readiness probes (/healthz, /readyz)
	//   - Metrics and webhook servers
	//   - Graceful shutdown (propagates ctx cancellation to all controllers)
	//
	// ctrl.GetConfigOrDie() reads the REST config:
	//   - In-cluster: uses the pod's service account token at /var/run/secrets/
	//   - Out-of-cluster (dev): falls back to ~/.kube/config
	// -------------------------------------------------------------------------
	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:                 scheme,
		Metrics:                metricsServerOptions,
		WebhookServer:          webhookServer,
		HealthProbeBindAddress: probeAddr,
		LeaderElection:         enableLeaderElection,
		// LeaderElectionID must be unique per operator in the cluster.
		// It is the name of the Lease object created in kube-system.
		LeaderElectionID: "1b19b2bb.earnix.com",
		// LeaderElectionReleaseOnCancel: true,
		// Uncomment to make the leader step down immediately on shutdown,
		// speeding up failover. Safe only if the process exits right after mgr.Start().
	})
	if err != nil {
		setupLog.Error(err, "unable to start manager")
		os.Exit(1)
	}

	// -------------------------------------------------------------------------
	// 6. Helm watcher
	// Reads Helm release data directly from Kubernetes Secrets (how Helm v3
	// stores releases). Used by the reconciler to detect outdated charts and
	// to verify if a release has been upgraded (auto-delete logic).
	// Needs mgr.GetConfig() to build its own typed k8s client for the Helm
	// storage driver (which requires a corev1.SecretInterface, not the generic
	// controller-runtime client).
	// -------------------------------------------------------------------------
	helmWatcher, err := helm.NewWatcher(mgr.GetConfig())
	if err != nil {
		setupLog.Error(err, "unable to create helm watcher")
		os.Exit(1)
	}

	// -------------------------------------------------------------------------
	// 7. AI enricher (optional)
	// Calls the Claude API to produce a structured RiskReport: upgrade path,
	// breaking changes, CVEs fixed, risk score, and recommended action.
	//
	// Enabled by setting ANTHROPIC_API_KEY in the pod's environment:
	//   kubectl create secret generic eol-operator-secrets \
	//     --from-literal=ANTHROPIC_API_KEY=sk-ant-...
	// Then reference it in the Deployment env block.
	//
	// If the key is absent the reconciler still fires notifications — it just
	// uses a minimal fallback report instead of the AI-generated one.
	// -------------------------------------------------------------------------
	var enricher *agent.AIEnricher
	if apiKey := os.Getenv("ANTHROPIC_API_KEY"); apiKey != "" {
		enricher = agent.NewAIEnricher(apiKey)
		setupLog.Info("AI enrichment enabled")
	} else {
		setupLog.Info("ANTHROPIC_API_KEY not s— AI enrichment disabled")
	}

	// -------------------------------------------------------------------------
	// 8. Notification channels (optional, additive)
	// Each channel is activated only when its env var is present.
	// You can enable multiple channels simultaneously — all active notifiers
	// are called for every alert. Add new notifiers here by following the same
	// env-var pattern.
	// -------------------------------------------------------------------------
	var notifiers []notifier.Notifier

	// Teams: Power Automate HTTP trigger webhook URL.
	// Create via: flow.microsoft.com → Instant cloud flow → "When an HTTP request
	// is received". Set TEAMS_WEBHOOK_URL to the generated POST URL.
	if webhookURL := os.Getenv("TEAMS_WEBHOOK_URL"); webhookURL != "" {
		notifiers = append(notifiers, notifier.NewTeamsNotifier(webhookURL))
		setupLog.Info("Teams notifications enabled")
	}

	// PagerDuty: Events API v2 integration routing key.
	// Create via: PagerDuty → Services → <service> → Integrations → Events API v2.
	// PD_MIN_SEVERITY controls the minimum severity that triggers a page:
	//   "minor" = page on everything, "major" = skip minor patches (default),
	//   "eol"   = only page when the release is two+ major versions behind.
	if routingKey := os.Getenv("PD_ROUTING_KEY"); routingKey != "" {
		minSeverity := os.Getenv("PD_MIN_SEVERITY")
		notifiers = append(notifiers, notifier.NewPagerDutyNotifier(routingKey, minSeverity))
		setupLog.Info("PagerDuty notifications enabled", "minSeverity", minSeverity)
	}

	// -------------------------------------------------------------------------
	// 9. Register the HelmEOLAlert reconciler with the Manager.
	// SetupWithManager registers:
	//   - For(HelmEOLAlert) — watches HelmEOLAlert CRDs for create/update/delete
	//   - Watches(Secret, owner=helm) — watches Helm release Secrets so we detect
	//     new installs and upgrades even before an alert CRD exists.
	// The reconciler is the main controller loop defined in
	// internal/controller/helmeolalert_controller.go.
	// -------------------------------------------------------------------------
	if err := (&controller.HelmEOLAlertReconciler{
		Client:    mgr.GetClient(), // shared caching k8s client (read/write CRDs, etc.)
		Scheme:    mgr.GetScheme(), // type registry — needed to decode objects
		Watcher:   helmWatcher,     // Helm release reader (direct Secret access)
		Enricher:  enricher,        // Claude AI enricher (nil = disabled)
		Notifiers: notifiers,       // active notification channels (Teams, PD, etc.)
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "HelmEOLAlert")
		os.Exit(1)
	}
	// +kubebuilder:scaffold:builder

	// -------------------------------------------------------------------------
	// 10. Register cert watchers as Manager runnables (if active).
	// mgr.Add() registers any object that implements the Runnable interface
	// (has a Start(ctx) method). The Manager starts them alongside controllers
	// and stops them on shutdown. This ensures cert watchers are lifecycle-managed
	// the same way as everything else.
	// -------------------------------------------------------------------------
	if metricsCertWatcher != nil {
		setupLog.Info("Adding metrics certificate watcher to manager")
		if err := mgr.Add(metricsCertWatcher); err != nil {
			setupLog.Error(err, "unable to add metrics certificate watcher to manager")
			os.Exit(1)
		}
	}

	if webhookCertWatcher != nil {
		setupLog.Info("Adding webhook certificate watcher to manager")
		if err := mgr.Add(webhookCertWatcher); err != nil {
			setupLog.Error(err, "unable to add webhook certificate watcher to manager")
			os.Exit(1)
		}
	}

	// -------------------------------------------------------------------------
	// 11. Health and readiness probes
	// Kubernetes uses these HTTP endpoints to manage the pod lifecycle:
	//   /healthz (liveness)  — if this fails, k8s restarts the pod
	//   /readyz (readiness)  — if this fails, k8s stops sending traffic to the pod
	// healthz.Ping just returns 200 OK — sufficient for a stateless operator.
	// -------------------------------------------------------------------------
	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {
		setupLog.Error(err, "unable to set up health check")
		os.Exit(1)
	}
	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
		setupLog.Error(err, "unable to set up ready check")
		os.Exit(1)
	}

	// -------------------------------------------------------------------------
	// 12. Start the Manager (blocking)
	// ctrl.SetupSignalHandler() returns a context that is cancelled on SIGTERM
	// or SIGINT. The Manager propagates this to all controllers and runnables,
	// giving them a chance to finish in-flight reconciliations before the process
	// exits. This is what makes graceful pod shutdown work correctly.
	// -------------------------------------------------------------------------
	setupLog.Info("starting manager")
	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
		setupLog.Error(err, "problem running manager")
		os.Exit(1)
	}
}
